name: github_tracker
description: A Dart utility to track popularity of GitHub projects.

environment:
  sdk: '>=2.12.0-0.0.dev <3.0.0'

dependencies:
  args: 
    git:
      url: https://github.com/dart-lang/args.git
      ref: null_safety
  github: ^7.0.3
  http: ^0.12.2
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  lint: ^1.2.0